[package]
name = "vespertide-schema-gen"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
schemars = "1.1"
serde_json = "1"
vespertide-core = { workspace = true }

